# Generated by Django 3.2.5 on 2021-10-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20210920_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
    ]
