# Generated by Django 3.2.5 on 2021-10-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20211022_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='name',
        ),
    ]
