# Generated by Django 3.2.5 on 2021-10-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20211026_1106'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='club',
            table='clubs',
        ),
        migrations.AlterModelTable(
            name='continent',
            table='continents',
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
        migrations.AlterModelTable(
            name='position',
            table='positions',
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('players', models.ManyToManyField(to='football.Player')),
            ],
            options={
                'db_table': 'user_teams',
                'ordering': ['id'],
            },
        ),
    ]
