# Generated by Django 3.2.5 on 2021-10-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_auto_20211026_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.club'),
        ),
    ]
