# Generated by Django 3.2.5 on 2021-11-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_userteam_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='positions',
        ),
    ]
